export interface Playlist {
    id: string;
    albumId: number;
    title: string;
    color: string;
    cover: string;
    artists: string[];
    description: string;
    pinned: boolean;
    duration: string;
}

export const playlists: Playlist[] = [
    {
        id: '1',
        albumId: 1,
        title: "Afternoon Jazz",
        color: "#982820ff",
        cover: "https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353",
        artists: ["Lofi Records"],
        description: "Dive into the smooth melodies of Afternoon Jazz, curated by Lofi Records.",
        pinned: true,
        duration: "about 15 min",
    },
    {
        id: '2',
        albumId: 2,
        title: "Chill Session",
        color: "#6050c8ff",
        cover: "https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693312187",
        artists: ["Lofi Records"],
        description: "Relax and unwind with Chill Session, a soothing blend of beats and melodies from Lofi Records.",
        pinned: true,
        duration: "about 15 min",
    },
    {
        id: '3',
        albumId: 3,
        title: "Study Session",
        color: "#e04858ff",
        cover: "https://f4.bcbits.com/img/a1435058381_65.jpg",
        artists: ["Lofi Records"],
        description: "Enhance your focus and productivity with Study Session, a curated playlist by Lofi Records.",
        pinned: true,
        duration: "about 15 min",
    },
    {
        id: '4',
        albumId: 4,
        title: "Blue Note",
        color: "#58b0c8ff",
        cover: "https://f4.bcbits.com/img/a1962013209_16.jpg",
        artists: ["Lucie Cravero", "HoKø"],
        description: "Immerse yourself in the soulful vibes of Blue Note, featuring Lucie Cravero and HoKø.",
        pinned: false,
        duration: "about 15 min",
    },
    {
        id: '5',
        albumId: 5,
        title: "Down Hill",
        color: "#302870ff",
        cover: "https://f4.bcbits.com/img/a2793859494_16.jpg",
        artists: ["Chau Sara"],
        description: "Experience the laid-back grooves of Down Hill, a collection of tracks by Chau Sara.",
        pinned: false,
        duration: "about 15 min",
    },
    {
        id: '6',
        albumId: 6,
        title: "Like a Necessity",
        color: "#f89828ff",
        cover: "https://f4.bcbits.com/img/a0363730459_16.jpg",
        artists: ["Swink"],
        description: "Discover the essential sounds of Like a Necessity, brought to you by Swink.",
        pinned: false,
        duration: "about 15 min",
    },
];

export interface Song {
    id: number;
    albumId: number;
    title: string;
    image: string;
    artists: string[];
    album: string;
    duration: string;
};

export const songs: Song[] = [
    {
        "id": 1,
        "albumId": 1,
        "title": "The Player",
        "image": `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
        "artists": ["Cosmic Koala", "Paul Indigo", "Lucid Keys"],
        "album": "Afternoon Jazz",
        "duration": "2:33",
    },
    {
        "id": 2,
        "albumId": 1,
        "title": "Nuit Douce",
        "image": `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
        "artists": ["Phlocalyst", "Myríad"],
        "album": "Afternoon Jazz",
        "duration": "2:33",
    },
    {
        "id": 3,
        "albumId": 1,
        "title": "Reflection",
        "image": `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
        "artists": ["HoKø", "Yoann Garel", "Damien Fleau"],
        "album": "Afternoon Jazz",
        "duration": "2:25",
    },
    {
        "id": 4,
        "albumId": 1,
        "title": "Gentle Rain",
        "image": `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
        "artists": ["softy", "Otis Ubaka", "Comodo"],
        "album": "Afternoon Jazz",
        "duration": "2:35",
    },
    {
        "id": 5,
        "albumId": 1,
        "title": "Blissful",
        "image": `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
        "artists": ["Krynoze", "Two Scents"],
        "album": "Afternoon Jazz",
        "duration": "2:45",
    },
    {
        "id": 1,
        "albumId": 2,
        "title": "Lightyears",
        "image": `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693312187`,
        "artists": ["Akraa"],
        "album": "2 A.M Chill Session",
        "duration": "2:26",
    },
    {
        "id": 2,
        "albumId": 2,
        "title": "Analogue Pulsar",
        "image": `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693312187`,
        "artists": ["Virtua", "Robert Iver"],
        "album": "2 A.M Chill Session",
        "duration": "3:02",
    },
    {
        "id": 3,
        "albumId": 2,
        "title": "Starwave",
        "image": `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693312187`,
        "artists": ["Soundgo"],
        "album": "2 A.M Chill Session",
        "duration": "3:13",
    },
    {
        "id": 4,
        "albumId": 2,
        "title": "Infuse",
        "image": `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693312187`,
        "artists": ["Forhill", "Eagle Eyed Tiger"],
        "album": "2 A.M Chill Session",
        "duration": "2:50",
    },
    {
        "id": 5,
        "albumId": 2,
        "title": "Echodrift",
        "image": `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693312187`,
        "artists": ["VIQ", "Krosia"],
        "album": "2 A.M Chill Session",
        "duration": "3:17",
    },
    {
        "id": 1,
        "albumId": 3,
        "title": "Glowing Lights",
        "image": `https://f4.bcbits.com/img/a1435058381_65.jpg`,
        "artists": ["No Spirit"],
        "album": "3 Am. Study Session",
        "duration": "2:45",
    },
    {
        "id": 2,
        "albumId": 3,
        "title": "Somewhere Else",
        "image": `https://f4.bcbits.com/img/a1435058381_65.jpg`,
        "artists": ["dryhope"],
        "album": "3 Am. Study Session",
        "duration": "2:35",
    },
    {
        "id": 3,
        "albumId": 3,
        "title": "Sheets",
        "image": `https://f4.bcbits.com/img/a1435058381_65.jpg`,
        "artists": ["E I S U"],
        "album": "3 Am. Study Session",
        "duration": "2:00",
    },
    {
        "id": 4,
        "albumId": 3,
        "title": "Phantasm",
        "image": `https://f4.bcbits.com/img/a1435058381_65.jpg`,
        "artists": ["Casiio", "Sleepermane"],
        "album": "3 Am. Study Session",
        "duration": "2:04",
    },
    {
        "id": 5,
        "albumId": 3,
        "title": "After Sunset",
        "image": `https://f4.bcbits.com/img/a1435058381_65.jpg`,
        "artists": ["Project AER", "WYS"],
        "album": "3 Am. Study Session",
        "duration": "2:40",
    },
    {
        "id": 1,
        "albumId": 4,
        "title": "Travel Melody",
        "image": "https://f4.bcbits.com/img/a1962013209_16.jpg",
        "artists": ["HoKø", "Lucie Cravero"],
        "album": "Blue Note",
        "duration": "2:03",
    },
    {
        "id": 2,
        "albumId": 4,
        "title": "Evening Colors",
        "image": "https://f4.bcbits.com/img/a1962013209_16.jpg",
        "artists": ["HoKø", "Damien Fleau", "Lucie Cravero"],
        "album": "Blue Note",
        "duration": "2:12",
    },
    {
        "id": 3,
        "albumId": 4,
        "title": "Bords de Marne",
        "image": "https://f4.bcbits.com/img/a1962013209_16.jpg",
        "artists": ["HoKø", "Lucie Cravero"],
        "album": "Blue Note",
        "duration": "2:10",
    },
    {
        "id": 4,
        "albumId": 4,
        "title": "Lying in the Grass",
        "image": "https://f4.bcbits.com/img/a1962013209_16.jpg",
        "artists": ["HoKø", "Lucie Cravero"],
        "album": "Blue Note",
        "duration": "2:32",
    },
    {
        "id": 5,
        "albumId": 4,
        "title": "Reborn",
        "image": "https://f4.bcbits.com/img/a1962013209_16.jpg",
        "artists": ["HoKø", "Lucie Cravero"],
        "album": "Blue Note",
        "duration": "2:36",
    },
    {
        "id": 1,
        "albumId": 5,
        "title": "Felucia",
        "image": "https://f4.bcbits.com/img/a2793859494_16.jpg",
        "artists": ["Chau Sara"],
        "album": "Down Hill",
        "duration": "1:52",
    },
    {
        "id": 2,
        "albumId": 5,
        "title": "Altara",
        "image": "https://f4.bcbits.com/img/a2793859494_16.jpg",
        "artists": ["Chau Sara"],
        "album": "Down Hill",
        "duration": "1:50",
    },
    {
        "id": 3,
        "albumId": 5,
        "title": "Nelyth",
        "image": "https://f4.bcbits.com/img/a2793859494_16.jpg",
        "artists": ["Chau Sara"],
        "album": "Down Hill",
        "duration": "2:04",
    },
    {
        "id": 4,
        "albumId": 5,
        "title": "Arsanis",
        "image": "https://f4.bcbits.com/img/a2793859494_16.jpg",
        "artists": ["Chau Sara"],
        "album": "Down Hill",
        "duration": "1:59",
    },
    {
        "id": 5,
        "albumId": 5,
        "title": "Treya",
        "image": "https://f4.bcbits.com/img/a2793859494_16.jpg",
        "artists": ["Chau Sara"],
        "album": "Down Hill",
        "duration": "1:48",
    },
    {
        "id": 1,
        "albumId": 6,
        "title": "First Encounter",
        "image": `https://f4.bcbits.com/img/a0363730459_16.jpg`,
        "artists": ["Swink", "møndberg"],
        "album": "Like a Necessity",
        "duration": "2:16",
    },
    {
        "id": 2,
        "albumId": 6,
        "title": "In Front Of Me",
        "image": `https://f4.bcbits.com/img/a0363730459_16.jpg`,
        "artists": ["Swink"],
        "album": "Like a Necessity",
        "duration": "2:04",
    },
    {
        "id": 3,
        "albumId": 6,
        "title": "My Dear",
        "image": `https://f4.bcbits.com/img/a0363730459_16.jpg`,
        "artists": ["Swink"],
        "album": "Like a Necessity",
        "duration": "2:20",
    },
    {
        "id": 4,
        "albumId": 6,
        "title": "When The Winter Comes",
        "image": `https://f4.bcbits.com/img/a0363730459_16.jpg`,
        "artists": ["Swink"],
        "album": "Like a Necessity",
        "duration": "1:54",
    },
    {
        "id": 5,
        "albumId": 6,
        "title": "Go Back In Time",
        "image": `https://f4.bcbits.com/img/a0363730459_16.jpg`,
        "artists": ["Swink"],
        "album": "Like a Necessity",
        "duration": "2:04",
    },
];